controller_manager:
  ros__parameters:
    update_rate: 10

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - joint_1
        - joint_2
        - joint_3
      command_interfaces:
        - position
      state_interfaces:
        - position
      open_loop_control: true
      allow_integration_in_goal_trajectories: true

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - joint_4
        - joint_5
      command_interfaces:
        - position
      state_interfaces:
        - position
      open_loop_control: true
      allow_integration_in_goal_trajectories: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
