planning_pipelines:
  pipeline_names: ["ompl"]

plan_request_params:
  planning_id: ompl
  planning_attempts: 5
  planning_pipeline: ompl
  planning_time: 10.0
  max_velocity_scaling_factor: 0.3
  max_acceleration_scaling_factor: 0.3
  smoothing_type: time_optimal